### ISSUE TITLE
How to make plugins?

### ISSUE THREAD

**Issue by 3oheicrw** [smallbasic/smallbasic.plugins#2]
I wanted to make a plugin but didn't find any documents or samples. I have read some plugins source but still don't know where to start. Please help.

**Comment by Joe7M** [comment]
I wrote a plugin for SmallBASIC for the Raspberry Pi: https://github.com/Joe7M/SmallBasicPIGPIO

In the src directory is a quite simple Makefile. For making a plugin you just need the following files:
- config
- hashmap.cpp
- hashmap.h
- main.cpp
- module.h
- param.cpp
- param.h
- var.h

in main.cpp you can define the functions/sub names in SmallBASIC with min and max parameters and the C-function which should be called. Have a look to gpio.c to see how to receive parameters and how to return a result. For example:

```
int Pin = get_param_int(argc, params, 0, 0);
int HighLow = get_param_int(argc, params, 1, 0);
```
Pin will be the value of the first parameter. Default value is 0. HighLow will be the value of the second parameter. Default value is 0. For every datatype in SmallBASIC a get_param-function exist. Have a look to param.h. If you want to get a matrix as parameter have a look to ssd1306.c -> BASIC_CMD_SSD1306_CopyToDisplay or a string ssd1306.c -> BASIC_CMD_SSD1306_Print

```
v_setint(retval, gpioRead(Pin));
```
will return the value of gpioRead(Pin) the SmallBASIC function. Also here exist a function for every datatype.

I hope it will help you a little bit.
